---
apiVersion: v1
kind: Service
metadata:
  name: node-hello-world
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31234
  selector:
    app: node-hello-world
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
        - name: node-hello-world
          image: odrodrig/node-app:latest
          ports:
            - name: http-port
              containerPort: 8080
